// Keep Thi's original TypeScript unchanged; generate the JS used by Node >=20.
import fs from 'node:fs';
import ts from 'typescript';

const source = new URL('../server/leash/vendor/jev-check.ts', import.meta.url);
const target = new URL('../server/leash/vendor/jev-check.js', import.meta.url);
const { outputText } = ts.transpileModule(fs.readFileSync(source, 'utf8'), {
  compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ES2022 },
});
const generated = '// Generated by npm run build:jev. Edit the original TypeScript, not this file.\n' + outputText;
if (process.argv.includes('--check')) {
  if (fs.readFileSync(target, 'utf8') !== generated) throw new Error('Jev source and generated JS differ. Run npm run build:jev.');
} else fs.writeFileSync(target, generated);
